# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - sticky-notes

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Build with dotnet
      run: dotnet build Notes.Api/Notes.Api.csproj --configuration Release

    - name: dotnet publish
      run: dotnet publish Notes.Api/Notes.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'sticky-notes'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_15fa3e27f13d495eba193f8851d55253 }}
        package: ${{env.DOTNET_ROOT}}/myapp